//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_07
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public System.DateTime Birthday { get; set; }
        public int HomeAddressId { get; set; }
        public int HighSchoolId { get; set; }
        public int Course { get; set; }
        public string Speciality { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        public virtual HighSchools HighSchools { get; set; }
    }
}
